name: "Execute Listing"

on:
  workflow_dispatch:
    inputs:
      listing:
        type: string
        description: 'Listing number (e.g. 2.1)'
        required: true

jobs:
  execute-listing:
    name: "Executing listing ${{ github.event.inputs. }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        run: |
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          cd ch02/listing_${{ github.event.inputs. }} 
          go mod tidy
          ./run.sh
          

