name: "Execute Listing"

on:
  workflow_dispatch:
    inputs:
      listing:
        type: string
        description: 'Listing number (e.g. 2.1)'
        required: true

jobs:
  execute-listing:
    name: "Executing listing ${{ github.event.inputs.listing }}"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: Run
        run: |
          cd ch02/listing_${{ github.event.inputs.listing }}
          echo "Current directory is $(pwd)"
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          
          go mod tidy
          ./run.sh
          

